[project]
name = "test-therapy-app"
version = "0.1.0"
description = "A test project for a Flask part-time position at Charleston Children's Therapy Center."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask==2.3",
    "flask-sqlalchemy>=3.1.1"
]
